#!/usr/bin/env php
<?php

echo $argv[1] . ' stage tests should cover 100% lines - ';

$report = file_get_contents('build/logs/coverage.txt');

if (!strpos($report, 'Lines:   100.00%')) {
    echo 'FAILED' . PHP_EOL;
    exit(1);
}

echo 'OK' . PHP_EOL;
